version: '3.1'

services:

  postgresql:
    image: postgres
    container_name: Postgresql
    restart: always
    ports:
        - 5432:5432
    environment:
      POSTGRES_USERNAME: admin
      POSTGRES_PASSWORD: 1wttqvly
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
   postgresql-data:
