version: '3.1'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    restart: always
    ulimits:
          memlock:
            soft: -1
            hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node